### ISSUE TITLE
[BUG] Send Video In DM Is Not Working

### ISSUE THREAD

**Issue by steffyjk** [adw0rd/instagrapi#2216]
**Sending a direct video message using instagrapi fails with the error:**

**❌ Failed to send video: This feature is no longer supported.**

**To Reproduce**
Here's the code snippet used to send the video:

```
message = client.direct_send_video(
    path=media_url,
    thread_ids=[thread_id]
)

suffix = Path(file.filename).suffix or ".mp4"
with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp_file:
    tmp_file.write(file_data)
    temp_file_path = Path(tmp_file.name)

```
**Traceback**
There was no detailed traceback, but the function raises:

❌ Failed to send video: This feature is no longer supported.

Expected behavior
Expected the direct_send_video() function to send a video to the specified thread ID successfully.

Desktop (please complete the following information):
OS: [e.g. Ubuntu 22.04]
Python version: [e.g. 3.12.6]
instagrapi version: [latest]
moveipy version: [latest]

**Comment by tutozz** [comment]
same here, i think instagram changed endpoint

Traceback (most recent call last):
  File "/home/---/venv311/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "/home/---/venv311/lib/python3.11/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/direct_v2/threads/broadcast/configure_video/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/---/talkWithMe/instagram_dm_bot.py", line 303, in send_video_to_thread
    msg = self.client.direct_send_video(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/---/venv311/lib/python3.11/site-packages/instagrapi/mixins/direct.py", line 507, in direct_send_video
    return self.direct_send_file(path, user_ids, thread_ids, content_type="video")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/---/venv311/lib/python3.11/site-packages/instagrapi/mixins/direct.py", line 580, in direct_send_file
    result = self.private_request(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/---/venv311/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 550, in private_request
    raise e
  File "/home/---/venv311/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 535, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/---/venv311/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 457, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: This feature is no longer supported.

**Comment by subzeroid** [comment]
This looks like a valid current bug report.

The useful part here is the concrete server-side response:
- `400` on `direct_v2/threads/broadcast/configure_video/`
- `UnknownError: This feature is no longer supported.`

That makes endpoint drift a plausible explanation for the current `direct_send_video()` path, rather than this being only a local dependency/setup issue.

Leaving this open. The likely next step is to compare the current DM video send path against a fresh Instagram app flow / HAR and see what replaced or changed around `configure_video`.

**Comment by subzeroid** [comment]
Fixed in c564a68.

What changed:
- `direct_send_video()` no longer uses `direct_v2/threads/broadcast/configure_video/`, which was returning `400 This feature is no longer supported`
- it now routes video sends through the existing `video_upload_to_direct(...)` story-direct flow
- `user_ids` are resolved through an existing direct thread first; if no thread is found, the method now fails explicitly with `DirectThreadNotFound` instead of the old dead-end server response

Regression coverage added for:
- direct video send with `thread_ids`
- direct video send with `user_ids` resolved to an existing thread
- missing existing thread for `user_ids`

Verified with: `.venv/bin/python -m unittest tests.DirectMixinRegressionTestCase`

I have not done a fresh live Instagram verification yet, so I am leaving the issue open until that is confirmed.

**Comment by subzeroid** [comment]
Live status update on current master: the old failing endpoint from this report is no longer used.

What I verified:
- `direct_send_video(...)` now goes through the direct-story upload path instead of `direct_v2/threads/broadcast/configure_video/`
- the live probe reached `media/configure_to_story/?video=1`
- multiple pair attempts failed there with repeated server-side 500 responses: `RetryError: ... /api/v1/media/configure_to_story/?video=1 (Caused by ResponseError('too many 500 error responses'))`

So this should stay open. The previous fix removed the retired `configure_video/` dead endpoint, but direct video sending is still not live-verified working. The next useful artifact is a sanitized current-app capture of sending a video in Direct, especially the upload/configure endpoint and payload that replaced or supplements this flow.

**Comment by alexgodlewski** [comment]
Captured the new endpoint via mitmproxy from a live IG Android app on 2026-05-06. Posting findings here in case it helps.

## Confirming current master is still broken

Reproduced: `direct_send_video()` now goes through `video_upload_to_direct()` → `media/configure_to_story/?video=1` and gets repeated 500s (`RetryError: Max retries exceeded ... too many 500 error responses`). That's the **story** endpoint, not direct, which is why it fails.

## The new endpoint

IG migrated direct video to:

```
POST https://i.instagram.com/api/v1/direct_v2/threads/broadcast/raven_attachment/?video=1
```

with a **signed body** (not URL-encoded plain). The upload itself moved to FB-domain rupload (same family as the voice path):

```
GET  https://rupload.facebook.com/messenger_video/{32hex}-{seg}-{size}-{ms}-{ms}
       → {"dc":"...","offset":N}
POST same URL with raw mp4 bytes
       → {"media_id": <int>, "id": 0}     ← becomes attachment_fbid
```

Then the broadcast carries `attachment_fbid: media_id` AND `video_result: media_id` (both equal), plus the usual thread/uuid/device fields, plus camera/composer cosmetics (clips list, edits, media_transformation_info, source_width/height, etc. — most are optional but the captured request had them).

Critical detail: requests to `rupload.facebook.com` need only the captured allow-list of headers. `self.private`'s ~30 pinned IG-mobile headers (`X-IG-*`, `X-Bloks-*`, `X-Pigeon-*`, `Host: i.instagram.com`, etc.) leak through `requests.Session.headers` merging and cause FB rupload to return a generic 404. A fresh `requests.Session` with only the captured allowlist works.

The mobile app's FB-domain calls also enforce **native mbedtls cert pinning inside `libstartup.so`** — neither HTTP Toolkit's bundled bypass nor `frida-multiple-unpinning` cover it. I bypassed it with a 4-byte static patch at vaddr `0x3d3b2c` (changed `cbz w0, #0x3d3b88` → `b #0x3d3b88`, inside the mbedtls handshake state machine right after the X.509 verify call). Pure-Python patching with `capstone` + `pyelftools`, then mitmproxy worked normally.

## Implementation in PR #2450

I've put the working implementation up at #2450 (the same PR also adds `direct_send_voice()` for #2447 — same general 3-step shape applies to both audio and video, just different endpoint names and one uses `with_signature=True` while the other doesn't).

Live-verified end-to-end against `socialflow.pl → @alexgodlewsky`:
- `GET 200` (offset=0)
- `POST 200` returns `{"media_id": 1745927176572205, "id": 0}`
- `POST raven_attachment/?video=1` returns `{"status": "ok", "action": "item_ack", "payload": {"item_id": "...", "msg_id": "mid.$cAAA..."}}`

Video bubble plays correctly in the recipient's IG.

Happy to iterate on the implementation if there are style/structure concerns. The endpoint name, payload shape, and FB-rupload path are captured byte-for-byte from the live app.

**Comment by subzeroid** [comment]
Fixed by https://github.com/subzeroid/instagrapi/pull/2450.

Code links:
- merge commit: https://github.com/subzeroid/instagrapi/commit/9e226a598bb25c870aaa23ab2b6aae6180232b5d
- maintainer follow-up commit: https://github.com/subzeroid/instagrapi/commit/c0284ab7c60a10291a4f83762f3c0521583a8728
- CI hotfix commit: https://github.com/subzeroid/instagrapi/commit/c92be79

What changed:
- `direct_send_video(...)` no longer uses the retired `direct_v2/threads/broadcast/configure_video/` endpoint
- video upload now uses the current FB-domain rupload path and broadcasts through `direct_v2/threads/broadcast/raven_attachment/?video=1`
- `thread_ids` and `user_ids` paths are both covered; `user_ids` resolution uses the returned direct thread before broadcast
- video metadata probing was adjusted to avoid the Package workflow security failure from raw subprocess usage

Verified after merge:
- live direct media coverage for `direct_send_video(...)` via both `thread_ids` and `user_ids`
- local direct regression tests
- Package workflow: https://github.com/subzeroid/instagrapi/actions/runs/25527109903
- CodeQL workflow: https://github.com/subzeroid/instagrapi/actions/runs/25527109919
