### ISSUE TITLE
post caption not showing

### ISSUE THREAD

**Issue by alosoft** [adw0rd/instagrapi#307]
**Describe the bug**
am able to post to IG but the picture or video does not show the caption

**To Reproduce**
`client.photo_upload(image_path, caption='Love you')`

 - instagrapi version: 2.0.2

**Comment by adw0rd** [comment]
@alosoft instagrapi maximum version 1.9.3
https://pypi.org/project/instagrapi/

But I'll see why the caption stopped working

**Comment by adw0rd** [comment]
Fixed instagrapi 1.9.4

**Comment by lexalevi4** [comment]
i updated to 1.9.4, but caption works several times, then don't work again. 
If i delete credentials file and relogin, it works again, but for a few times.

**Comment by alosoft** [comment]
@adw0rd the issue still persist. Its works sometimes in version 1.8.7. I will upgrade to 1.9.4 and report back

**Comment by mavenium** [comment]
I have this problem too. instagrapi version 1.16.14

**Comment by LatikeshAhire** [comment]
i am also facing the same issue. version 1.16.20 and 1.16.21

**Comment by Garr-tt** [comment]
Having the issue on 1.16.30

**Comment by NathanAdhitya** [comment]
Having the issue on 1.16.41

**Comment by adw0rd** [comment]
This does not depend on instagrapi, you are blocked by instagram for comment limits, why I don’t know, you have to figure it out yourself. Comments and post description are one type of data - comment
